name: Android CI - Release

on:
    push:
        branches: [ "master" ]

jobs:
  production-release:
    name: Build & deploy production
    env:
      SOFTPAY_NEXUS_USERNAME: ${{ secrets.SOFTPAY_NEXUS_USERNAME }}
      SOFTPAY_NEXUS_PASSWORD: ${{ secrets.SOFTPAY_NEXUS_PASSWORD }}
      SOFTPAY_INTEGRATOR_ID: ${{ secrets.SOFTPAY_INTEGRATOR_ID }}
      SOFTPAY_SANDBOX_ACCESS_ID: ${{ secrets.SOFTPAY_SANDBOX_ACCESS_ID }}
      SOFTPAY_SANDBOX_ACCESS_SECRET: ${{ secrets.SOFTPAY_SANDBOX_ACCESS_SECRET }}
    runs-on: tillhub-org-runner

    steps:
      - name: Checking out branch
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Run Detekt Code Analysis
        env:
          SOFTPAY_NEXUS_USERNAME: ${{ secrets.SOFTPAY_NEXUS_USERNAME }}
          SOFTPAY_NEXUS_PASSWORD: ${{ secrets.SOFTPAY_NEXUS_PASSWORD }}
          SOFTPAY_INTEGRATOR_ID: ${{ secrets.SOFTPAY_INTEGRATOR_ID }}
          SOFTPAY_SANDBOX_ACCESS_ID: ${{ secrets.SOFTPAY_SANDBOX_ACCESS_ID }}
          SOFTPAY_SANDBOX_ACCESS_SECRET: ${{ secrets.SOFTPAY_SANDBOX_ACCESS_SECRET }}
        run: ./gradlew detekt

      - name: Run Unit tests
        run: ./gradlew testDebug

      - name: Assemble release build
        run: ./gradlew assembleRelease

      - name: Deploy release build to Nexus
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: ./gradlew publish

#          # Hardware accelerated Android virtualization on Actions Linux larger hosted runners
#            - name: Enable KVM
#              run: |
#                echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
#                sudo udevadm control --reload-rules
#                sudo udevadm trigger --name-match=kvm
#
#            - name: Run Android tests
#              uses: reactivecircus/android-emulator-runner@v2
#              with:
#                api-level: 29
#                target: default
#                arch: x86_64
#                profile: Nexus 6
#                script: ./gradlew payment-engine:connectedCheck